### ISSUE TITLE
Readme documentation config issue

### ISSUE THREAD

**Issue by drewjenkel** [microsoft/healthkit-on-fhir#13]
On the documentation page (Readme.md) on the sample app, on the section "Configuring the application", a link to a config.json is present where the file is not there.

Upon starting the sample app, the documentation reads that a config.json file can be drug to the simulator screen, but an error in XCode reveals it is looking for it in the sample directory, even if it is dragged from some place like the desktop.

**Comment by namalu** [comment]
- The config.json link has been fixed.

- I believe the issue with dragging the config.json onto the simulator screen has been resolved. It looks like there may have been a bug in a previous version of Xcode.
