### ISSUE TITLE
Running sample using SMART on FHIR

### ISSUE THREAD

**Issue by agigary** [microsoft/healthkit-on-fhir#20]
Hi

I have been trying to use the sample app to connect to a FHIR service hosted in Azure, using SMART on FHIR via Azure AD using a "web" App Registration.

However I constantly get an issue with the redirect _uri in that the SMART on FHIR proxy seems to pass back a URI after a successful login via Azure, however the app never launches post sign in, I have checked all the plist settings and verified the build settings however the app will never load, its almost as if the AwaitingAuthCallback never triggers, from the SMART on FHIR proxy response however I am unsure as to why. 

I am keen to try and get this working, any ideas would be greatly received, one thought was is this due to the change in the AD App Registration from ADAL to MSAL authentication?

**Comment by agigary** [comment]
Hi Namalu

So the redirect url is currently coming back as : 
https://healthkitonfhir/callback?code=0.ATsAhm8_Yem2j02Hb-gwPWqhtb9xDyq6yGdLh29KHxmOKOI7ADQ.AQABAAIAAAD-DLA3VO7QrddgJg7WevrKcxEiWZEEozhiTSMa1eMOZ9Ag7VE3cVya0Ge_vQSOyhR9ZJJbh5t6F_McTtA5ndcR6nP1VweouNDBNYUbLGfIFZWvh90s9tiJSiEz9auMJ7gcj82clDfeDY1VmEXnLCZA42AWsJ2t97QhhhhTezGIuBwA2Q-T6811lX-SL3ZGWEHM5VG1k6mlKkPDgqQyjtKdyd7hsFjd05x_Sws4tzTq49E24sgytQ5E32Eqk1hn2T9oJyq-akg5E2_mMwFzvf31kbFXXGww14hUZxN24Bunktdjl39w4st0JUFuORxrHS_an5ffrACCXOJ-zgwZLeqfdqdP2jMxcJLiKpL8Gk2G0K5ycH6JpR0tGm6V2v4j84rqMnszQqVAwEzdPvuU5pCl_f80tvC73BtrSeSZugk2kSrPt1VB2q1yWuoKXis2ZfGnbZnF4O5YAGji4nuVd8sNdmH9HsS2YN05N9VqHUW-6-VNYIx-6A09s2gwIV6bVFCuv2pZ3F2IZoKUyHXklirLtrzagGnkABg1K84VtSwXCADd4BcABMOTfS8vPGoI0HtITvFiDlIh0RmJVYivX2mrDhCMnGm2SQhmcGfsi1FO6r8spgmlqbcgeOyhl4tbiogAA&state=CBE6CFE3&session_state=775bbbbe-0bf0-4ef6-9ce6-0a3afb2be012#, however it never then loads the application again to move past the login screen.

To get to the above I have appended an "https://" and also removed the "://callback" from the setup string in the code, otherwise when you build the string for the azure application using the SMART on FHIR Proxy redirect code. 

$replyUrl = "https://healthkitonfhir/callback"
$fhirServerUrl = "https://agihealthsocialcare-demo-fhir.fhir.azurehealthcareapis.com"
$bytes = [System.Text.Encoding]::UTF8.GetBytes($ReplyUrl)
$encodedText = [Convert]::ToBase64String($bytes)
$encodedText = $encodedText.TrimEnd('=');
$encodedText = $encodedText.Replace('/','_');
$encodedText = $encodedText.Replace('+','-');

$newReplyUrl = $FhirServerUrl.TrimEnd('/') + "/AadSmartOnFhirProxy/callback/" + $encodedText


You can't get past the MS auth process and just comes back with an error AADSTS50011 "Reply url in the request doesn't match the application configured"  So the initialise services function currently looks like: 

private func initializeServices() {
        // Create the SMART on FHIR client
        smartClient = Client(
            baseURL: URL(string: ConfigurationHelper.smartClientBaseUrl)!,
            settings: [ "client_id": ConfigurationHelper.smartClientClientId, "redirect": "https://" + AppDelegate.callbackScheme + "/callback" ]
        )

The plist entries are as standard:

<key>CFBundleURLTypes</key>
	<array>
		<dict>
			<key>CFBundleTypeRole</key>
			<string>Editor</string>
			<key>CFBundleURLName</key>
			<string>com.microsoft.HealthKitOnFhir-Sample</string>
			<key>CFBundleURLSchemes</key>
			<array>
				<string>healthkitonfhir</string>
			</array>
		</dict>
	</array>

Thanks for your help!

**Comment by agigary** [comment]
So I have traced it through potentially, I think the challenge is that the OAuth2 swift package sends the call back or redirect URL as"HealthKitOnFhir://" to enable the contextual app launch again on iOS once the authentication is approved. However Azure AD requires the Application redirect URI to begin with "https://" with out that you can't add it to the configuration in Azure. So in theory how can this ever work on as you need the "https://" to get through the initial authentication window and when the callback happens its sending "https://HealthKitOnFhir which will never work in iOS.

**Comment by namalu** [comment]
The [SMART on FHIR Proxy](https://docs.microsoft.com/en-us/azure/healthcare-apis/azure-api-for-fhir/use-smart-on-fhir-proxy) redirect URIs are a bit confusing; I will make a few assumptions, and you can correct me where I am wrong.

I assume you have set up an App Registration in Azure Active Directory (AAD) and added entries to the "Mobile and desktop applications" "Redirect URIs" section. Because you are using the SMART on FHIR Proxy, the actual redirect URI used to open the iOS Application needs to be Base64 Encoded and added to the SMART on FHIR Proxy URI. This is because the FHIR service forwards the request to AAD, then AAD responds to the proxy, and finally the proxy responds back to the client with the original redirect URI.

When I convert the redirect URI to the Base64 encoded value, I usually add 2 redirect URIs to handle a case where you may end up with a trailing forward slash.

healthkitonfhir://callback ==> aGVhbHRoa2l0b25maGlyOi8vY2FsbGJhY2s=
healthkitonfhir://callback/ ==> aGVhbHRoa2l0b25maGlyOi8vY2FsbGJhY2sv


Here is an example of what it should look like in your AAD App Registration:

```
https://******-fhir.fhir.azurehealthcareapis.com/AadSmartOnFhirProxy/callback/aGVhbHRoa2l0b25maGlyOi8vY2FsbGJhY2s=
https://******-fhir.fhir.azurehealthcareapis.com/AadSmartOnFhirProxy/callback/aGVhbHRoa2l0b25maGlyOi8vY2FsbGJhY2sv
```

You should not need to modify any code in the sample application if you use the values provided above.

**Comment by agigary** [comment]
So turns out you now need to now have a paid for apple provisioning profile to access the healthkit background delivery entitlement: https://stackoverflow.com/questions/68292935/how-do-i-add-this-entitlement-in-xcode-swift-com-apple-developer-healthkit-backg & https://stackoverflow.com/questions/69448289/healthkit-background-delivery-entitlements-ios-15

**Comment by namalu** [comment]
You don't need to pay for the specific provisioning profile, but rather, you need to join the [Apple Developer Program](https://developer.apple.com/support/compare-memberships/). It is $99 per year per account (not per person). Depending on your situation, you may also be eligible for a fee waiver.

I'm going to close this issue based on the fact that your original issue with logging in has been addressed. Thank you for your discovery that the background delivery entitlement is missing from the sample app. I will be updating the sample app to include the entitlement and improve the documentation about the requirement to have a paid developer account and Azure Active Directory SMART on FHIR Proxy.
